### PR TITLE
Reviews Section Completed

### LINKED ISSUE #17: create the reviews section

### PR DESCRIPTION
**Pull request by HarshDeep61034**
closes #17 

Desktop: 
Screenshot from 2023-08-09 00-25-24
Mobile:
Screenshot from 2023-08-09 00-25-57

### CODE REVIEW

**Review by Monilprajapati — CHANGES_REQUESTED** [review]
Try to follow the design @HarshDeep61034. This looks simpler and there is also css issue with footer like if click on next button on certain review the footer gets up and down. check it out.

Design::
image

**Comment by HarshDeep61034** [comment]
Bro if you want me to create that 3d effect i can't im not a css Master!
other than that there are almost identical, its just the font is diffrent.
and yeah the height is variable because the images and reviews were of diffrent shapes & sizes.
I'll see if can fix that.

**Comment by victorchrollo14** [comment]
I think the size problem is because of different image sizes, if images are  of same size there won't be any problem.
just fix of that issue with card going out of view at 768px, then we'll merge it up.

**Comment by HarshDeep61034** [comment]
> I think the size problem is because of different image sizes, if images are  of same size there won't be any problem.
> just fix of that issue with card going out of view at 768px, then we'll merge it up.
> 
> 
> 

On it sir 🫡

**Comment by HarshDeep61034** [comment]
@victorchrollo14 done bro!
check this:
Screenshot from 2023-08-09 19-19-44

**Comment by victorchrollo14** [comment]
looks fine. I'll merge it up

**Pull request merged**
