### PR TITLE
Login page done

### LINKED ISSUE #25: Build the login and registration component.
Both the login and Registration component will lie in the same section. 
you will be able to toggle between the login and registration within it.

This Section will appear when you click on account Icon.
Screenshot from 2023-08-05 16-47-28

### PR DESCRIPTION
**Pull request by HarshDeep61034**
finally the login page is done!
for now ive conditionally rendered Register & Login using a state.
let me know if you have any suggestion I'm open and willing to work.
fixes #25 
Screenshot from 2023-09-02 19-40-41
Screenshot from 2023-09-02 19-40-47

### CODE REVIEW

**Comment by victorchrollo14** [comment]
@HarshDeep61034 , we have changed the design a lil bit for the login and regitration part. We are going to have a seperate registration page and login page. You can look into figma [https://www.figma.com/file/figjD5PRyaAJ5ffTFVOMDN/Ecommerce-Site-Mern?type=design&node-id=38%3A383&mode=design&t=f6hRKvD5lZzcMaIv-1](url) . Most of it is same just add the side Image for desktop side and seperate the content for login and register logic plus add login with github as well.

**Comment by HarshDeep61034** [comment]
got it!

**Comment by HarshDeep61034** [comment]
@victorchrollo14 can you elaborate this failing check, the changes are done!

**Comment by victorchrollo14** [comment]
> @victorchrollo14 can you elaborate this failing check, the changes are done! 

I guess it has something to with deploying on vercel.

**Comment by victorchrollo14** [comment]
@HarshDeep61034 pull the changes from main branch into your login branch.

**Comment by victorchrollo14** [comment]
image
@HarshDeep61034 . the Image and register component seem to overlapping and their is too much whitespace between the navbar and the components , display those components a bit towards the navbar.
* There are some issues with responsiveness, which we can deal in another issue I guess.

**Comment by HarshDeep61034** [comment]
got it 👍🏼

**Comment by victorchrollo14** [comment]
> got it 👍🏼 if i will pull changes i will have to discard these commits.
You don't have to I guess, I've done that before it sync's in without any issues. 
Try pulling in the changes.

**Pull request merged**
