### PR TITLE
Homepage card issue

### LINKED ISSUE #16: create homepage product cards component.

### PR DESCRIPTION
**Pull request by HarshDeep61034**
closes #16

### CODE REVIEW

**Review by victorchrollo14 — CHANGES_REQUESTED** [review]
image
bro add a min-width for the images maybe around 250 - 300 would be fine, it's too small on mobile screen, scale the image till a max width of 400-450. break it into 2 rows at 600px or 768px and into three rows at 1024px

**Comment by HarshDeep61034** [comment]
I didn't understood how you wanted it to be, but i fixed the issue with from my POV.

**Comment by HarshDeep61034** [comment]
@victorchrollo14 @Monilprajapati check If its working

**Review by victorchrollo14 — COMMENTED** [review]
overall everything is fine.
You can make use of destructuring instead of using props.
I read that it's not a good practice to use index as key while rendering lists, you can make use of  crypto.randomuuid() which generates a unique index for you.

**Pull request merged**
